--------------------
Failed to process https://github.com/macias67/crm-tiendapaq.git repo
Traceback (most recent call last):
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 312, in generate_quality_report
    vnodes_expected_number=vnodes_expected_number)
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 135, in measure_quality
    (restarts, repository))
RuntimeError: Run out of 3 attempts. Failed to train proper model for https://github.com/macias67/crm-tiendapaq.git.
--------------------
Failed to process https://github.com/renesansz/release-based-workflow.git repo
Traceback (most recent call last):
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 312, in generate_quality_report
    vnodes_expected_number=vnodes_expected_number)
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 137, in measure_quality
    bblfsh=bblfsh, config_json=config)
  File "/lookout-sdk-ml/lookout/core/helpers/analyzer_context_manager.py", line 87, in review
    log_level=log_level, config_json=config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 101, in review
    return self._run("review", fr, to, port, git_dir, bblfsh, log_level, config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 131, in _run
    return subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/tmp/lookout-sdk-ml/lookout-sdk-v0.7.0', 'review', 'ipv4://localhost:23347', '--from', '4771dc77e4ff4650db503dc4b730b96670c715dc', '--to', '2319ddff83f085316b519d2de195e57650bb74d4', '--git-dir', '/tmp/top-repos-quality-repos-giskwsr0/release-based-workflow.git', '--log-format', 'json', '--log-level', 'warning', '--config-json', '{"style.format.analyzer.FormatAnalyzer": {"aggregate": true}}']' returned non-zero exit status 1.
--------------------
Failed to process https://github.com/learn-co-students/fewpjs-sending-data-with-fetch-re-coded_istanbul_web003.git repo
Traceback (most recent call last):
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 312, in generate_quality_report
    vnodes_expected_number=vnodes_expected_number)
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 137, in measure_quality
    bblfsh=bblfsh, config_json=config)
  File "/lookout-sdk-ml/lookout/core/helpers/analyzer_context_manager.py", line 87, in review
    log_level=log_level, config_json=config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 101, in review
    return self._run("review", fr, to, port, git_dir, bblfsh, log_level, config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 131, in _run
    return subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/tmp/lookout-sdk-ml/lookout-sdk-v0.7.0', 'review', 'ipv4://localhost:23347', '--from', '6808c4169b1ca3c6240fa9099dc39acb48f4dd0b', '--to', '408b62ac0ddcdf27c26c403423ba769a772f38a0', '--git-dir', '/tmp/top-repos-quality-repos-3dwk9hoy/fewpjs-sending-data-with-fetch-re-coded_istanbul_web003.git', '--log-format', 'json', '--log-level', 'warning', '--config-json', '{"style.format.analyzer.FormatAnalyzer": {"aggregate": true}}']' returned non-zero exit status 1.
--------------------
Failed to process https://github.com/learn-co-students/react-async-fetch-lab-nyc-web-033020.git repo
Traceback (most recent call last):
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 312, in generate_quality_report
    vnodes_expected_number=vnodes_expected_number)
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 137, in measure_quality
    bblfsh=bblfsh, config_json=config)
  File "/lookout-sdk-ml/lookout/core/helpers/analyzer_context_manager.py", line 87, in review
    log_level=log_level, config_json=config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 101, in review
    return self._run("review", fr, to, port, git_dir, bblfsh, log_level, config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 131, in _run
    return subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/tmp/lookout-sdk-ml/lookout-sdk-v0.7.0', 'review', 'ipv4://localhost:23347', '--from', '2e62eed7eafc0908852f462a97b2e17d3d055405', '--to', '2e62eed7eafc0908852f462a97b2e17d3d055405', '--git-dir', '/tmp/top-repos-quality-repos-qnpx4ia5/react-async-fetch-lab-nyc-web-033020.git', '--log-format', 'json', '--log-level', 'warning', '--config-json', '{"style.format.analyzer.FormatAnalyzer": {"aggregate": true}}']' returned non-zero exit status 1.
--------------------
Failed to process https://github.com/rienafairefr/pynynab.git repo
Traceback (most recent call last):
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 312, in generate_quality_report
    vnodes_expected_number=vnodes_expected_number)
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 137, in measure_quality
    bblfsh=bblfsh, config_json=config)
  File "/lookout-sdk-ml/lookout/core/helpers/analyzer_context_manager.py", line 87, in review
    log_level=log_level, config_json=config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 101, in review
    return self._run("review", fr, to, port, git_dir, bblfsh, log_level, config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 131, in _run
    return subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/tmp/lookout-sdk-ml/lookout-sdk-v0.7.0', 'review', 'ipv4://localhost:23347', '--from', 'c895e7b764358fb591002b11a457a95579d4157f', '--to', 'd5fc0749618409c6bb01cc2b93832cc59d780eaa', '--git-dir', '/tmp/top-repos-quality-repos-ehsrsk1k/pynynab.git', '--log-format', 'json', '--log-level', 'warning', '--config-json', '{"style.format.analyzer.FormatAnalyzer": {"aggregate": true}}']' returned non-zero exit status 1.
