--------------------
Failed to process https://github.com/bridgetklingler/jcp_payroll.git repo
Traceback (most recent call last):
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 312, in generate_quality_report
    vnodes_expected_number=vnodes_expected_number)
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 137, in measure_quality
    bblfsh=bblfsh, config_json=config)
  File "/lookout-sdk-ml/lookout/core/helpers/analyzer_context_manager.py", line 87, in review
    log_level=log_level, config_json=config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 101, in review
    return self._run("review", fr, to, port, git_dir, bblfsh, log_level, config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 131, in _run
    return subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/tmp/lookout-sdk-ml/lookout-sdk-v0.7.0', 'review', 'ipv4://localhost:10273', '--from', '3daa011c04dc82a94f5b59cb3d1aa9e17c9dde61', '--to', 'ff7d92d50176e4881316bfafd73f916122d11606', '--git-dir', '/tmp/top-repos-quality-repos-5nt700jd/jcp_payroll.git', '--log-format', 'json', '--log-level', 'warning', '--config-json', '{"style.format.analyzer.FormatAnalyzer": {"aggregate": true}}']' returned non-zero exit status 1.
--------------------
Failed to process https://github.com/chakra-core/chakracore.git repo
Traceback (most recent call last):
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 312, in generate_quality_report
    vnodes_expected_number=vnodes_expected_number)
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 137, in measure_quality
    bblfsh=bblfsh, config_json=config)
  File "/lookout-sdk-ml/lookout/core/helpers/analyzer_context_manager.py", line 87, in review
    log_level=log_level, config_json=config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 101, in review
    return self._run("review", fr, to, port, git_dir, bblfsh, log_level, config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 131, in _run
    return subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/tmp/lookout-sdk-ml/lookout-sdk-v0.7.0', 'review', 'ipv4://localhost:10273', '--from', 'e2ae5db9b79d221321437070b447139379d85c04', '--to', '4841a76a6a0c7c9c212846e8c96c8675ce7653da', '--git-dir', '/tmp/top-repos-quality-repos-oqvxm_qv/chakracore.git', '--log-format', 'json', '--log-level', 'warning', '--config-json', '{"style.format.analyzer.FormatAnalyzer": {"aggregate": true}}']' returned non-zero exit status 1.
--------------------
Failed to process https://github.com/acornapps/cocktail-manual.git repo
Traceback (most recent call last):
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 312, in generate_quality_report
    vnodes_expected_number=vnodes_expected_number)
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 137, in measure_quality
    bblfsh=bblfsh, config_json=config)
  File "/lookout-sdk-ml/lookout/core/helpers/analyzer_context_manager.py", line 87, in review
    log_level=log_level, config_json=config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 101, in review
    return self._run("review", fr, to, port, git_dir, bblfsh, log_level, config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 131, in _run
    return subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/tmp/lookout-sdk-ml/lookout-sdk-v0.7.0', 'review', 'ipv4://localhost:10273', '--from', '666122098dabfb39a47f0a94fbd7078ebdbba6e8', '--to', 'b2c81336970cb70e33c8a5d0787fe5b36f0b5b38', '--git-dir', '/tmp/top-repos-quality-repos-kcse085f/cocktail-manual.git', '--log-format', 'json', '--log-level', 'warning', '--config-json', '{"style.format.analyzer.FormatAnalyzer": {"aggregate": true}}']' returned non-zero exit status 1.
--------------------
Failed to process https://github.com/dannybarker/hair-shop-cap.git repo
Traceback (most recent call last):
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 312, in generate_quality_report
    vnodes_expected_number=vnodes_expected_number)
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 137, in measure_quality
    bblfsh=bblfsh, config_json=config)
  File "/lookout-sdk-ml/lookout/core/helpers/analyzer_context_manager.py", line 87, in review
    log_level=log_level, config_json=config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 101, in review
    return self._run("review", fr, to, port, git_dir, bblfsh, log_level, config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 131, in _run
    return subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/tmp/lookout-sdk-ml/lookout-sdk-v0.7.0', 'review', 'ipv4://localhost:10273', '--from', '1ac40595a94cc7f0e707ee7cf54c9e7102a1b550', '--to', 'c43ea6866b5e7f76895a194f42c8a1d549cc04bf', '--git-dir', '/tmp/top-repos-quality-repos-8d4xa0f_/hair-shop-cap.git', '--log-format', 'json', '--log-level', 'warning', '--config-json', '{"style.format.analyzer.FormatAnalyzer": {"aggregate": true}}']' returned non-zero exit status 1.
--------------------
Failed to process https://github.com/xgabe973/project3.git repo
Traceback (most recent call last):
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 312, in generate_quality_report
    vnodes_expected_number=vnodes_expected_number)
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 137, in measure_quality
    bblfsh=bblfsh, config_json=config)
  File "/lookout-sdk-ml/lookout/core/helpers/analyzer_context_manager.py", line 87, in review
    log_level=log_level, config_json=config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 101, in review
    return self._run("review", fr, to, port, git_dir, bblfsh, log_level, config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 131, in _run
    return subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/tmp/lookout-sdk-ml/lookout-sdk-v0.7.0', 'review', 'ipv4://localhost:10273', '--from', 'e36bbe20d2c6d101e7731a43480db1fdb7e3f456', '--to', '5cdbd162477789cd187071a8c056d2f1531018d3', '--git-dir', '/tmp/top-repos-quality-repos-grs_2gk2/project3.git', '--log-format', 'json', '--log-level', 'warning', '--config-json', '{"style.format.analyzer.FormatAnalyzer": {"aggregate": true}}']' returned non-zero exit status 1.
--------------------
Failed to process https://github.com/picholasnaridon/fcqa.git repo
Traceback (most recent call last):
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 312, in generate_quality_report
    vnodes_expected_number=vnodes_expected_number)
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 137, in measure_quality
    bblfsh=bblfsh, config_json=config)
  File "/lookout-sdk-ml/lookout/core/helpers/analyzer_context_manager.py", line 87, in review
    log_level=log_level, config_json=config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 101, in review
    return self._run("review", fr, to, port, git_dir, bblfsh, log_level, config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 131, in _run
    return subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/tmp/lookout-sdk-ml/lookout-sdk-v0.7.0', 'review', 'ipv4://localhost:10273', '--from', '3b955296572e57e7979e616ee5c68554de9808a0', '--to', 'a3b72620e7447076e3a3bd70015021d404e51661', '--git-dir', '/tmp/top-repos-quality-repos-ffdr3ai9/fcqa.git', '--log-format', 'json', '--log-level', 'warning', '--config-json', '{"style.format.analyzer.FormatAnalyzer": {"aggregate": true}}']' returned non-zero exit status 1.
--------------------
Failed to process https://github.com/learn-co-students/hogwarts-london-web-career-042219.git repo
Traceback (most recent call last):
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 312, in generate_quality_report
    vnodes_expected_number=vnodes_expected_number)
  File "/style-analyzer/lookout/style/format/benchmarks/quality_report.py", line 137, in measure_quality
    bblfsh=bblfsh, config_json=config)
  File "/lookout-sdk-ml/lookout/core/helpers/analyzer_context_manager.py", line 87, in review
    log_level=log_level, config_json=config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 101, in review
    return self._run("review", fr, to, port, git_dir, bblfsh, log_level, config_json)
  File "/lookout-sdk-ml/lookout/core/helpers/server.py", line 131, in _run
    return subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/tmp/lookout-sdk-ml/lookout-sdk-v0.7.0', 'review', 'ipv4://localhost:10273', '--from', '0cf8292da5cca38eff7a1584bc3a201623434566', '--to', 'f9d7c49cd83a18be963c26bfdbfefaa82010d1ce', '--git-dir', '/tmp/top-repos-quality-repos-1fk_km89/hogwarts-london-web-career-042219.git', '--log-format', 'json', '--log-level', 'warning', '--config-json', '{"style.format.analyzer.FormatAnalyzer": {"aggregate": true}}']' returned non-zero exit status 1.
